# Generated by Django 2.2.24 on 2022-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220317_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
